### ISSUE TITLE
Не работает конвертация

### ISSUE THREAD

**Issue by nobi-k** [Elfrey/elfrey-lss-converter#3]
Показывает начинаю Экспорт и больше не чего не посходит,

![image](https://github.com/user-attachments/assets/e99364a1-dade-4f6d-8040-2b14d4e69a65)

**Comment by Elfrey** [comment]
@nobi-k напиши версию системы, днд и приложи пожалуйста json персонажа, которого пытаешься экспортировать.

**Comment by codyspb** [comment]
Вот что в логах на dnd 4.1.2 fvtt 12

Начинаю экспорт.

foundry-esm.js:4621 Error: The `activation` property on `ActivatedEffectTemplate` has been deprecated.
Deprecated since Version DnD5e 4.0
Backwards-compatible support will be removed in Version DnD5e 4.4
    at Object.logCompatibilityWarning (foundry-esm.js:4609:19)
    at FeatData.get (activities.mjs:460:25)
    at module.js:1:7965
    at EmbeddedCollection.forEach (foundry-esm.js:5031:9)
    at module.js:1:7515
    at Object.callback (module.js:1:12499)
    at #onClickItem (foundry.js:68634:11)
    at HTMLElement.dispatch (jquery.min.js:2:40035)
    at ce.event.add.v.handle (jquery.min.js:2:38006)

logCompatibilityWarning @ foundry-esm.js:4621
get @ activities.mjs:460
(anonymous) @ module.js:1
forEach @ foundry-esm.js:5031
(anonymous) @ module.js:1
callback @ module.js:1
#onClickItem @ foundry.js:68634
dispatch @ jquery.min.js:2
ce.event.add.v.handle @ jquery.min.js:2Understand this warningAI
foundry-esm.js:4621 Error: The `getAttackToHit` method on `Item5e` has moved to `getAttackData` on `AttackActivity`.
Deprecated since Version DnD5e 4.0
Backwards-compatible support will be removed in Version DnD5e 4.4
    at Object.logCompatibilityWarning (foundry-esm.js:4609:19)
    at Item5e.getAttackToHit (item.mjs:715:19)
    at l (module.js:1:1690)
    at module.js:1:7838
    at EmbeddedCollection.forEach (foundry-esm.js:5031:9)
    at module.js:1:7515
    at Object.callback (module.js:1:12499)
    at #onClickItem (foundry.js:68634:11)
    at HTMLElement.dispatch (jquery.min.js:2:40035)
    at ce.event.add.v.handle (jquery.min.js:2:38006)

logCompatibilityWarning @ foundry-esm.js:4621
getAttackToHit @ item.mjs:715
l @ module.js:1
(anonymous) @ module.js:1
forEach @ foundry-esm.js:5031
(anonymous) @ module.js:1
callback @ module.js:1
#onClickItem @ foundry.js:68634
dispatch @ jquery.min.js:2
ce.event.add.v.handle @ jquery.min.js:2Understand this warningAI
module.js:1 Uncaught (in promise) TypeError: e.getDerivedDamageLabel is not a function
[Detected 1 package: elfrey-lss-converter(1.6.4)]
    at l (module.js:1:1921)
    at module.js:1:7838
    at EmbeddedCollection.forEach (foundry-esm.js:5031:9)
    at module.js:1:7515
    at Object.callback (module.js:1:12499)
    at #onClickItem (foundry.js:68634:11)
    at HTMLElement.dispatch (jquery.min.js:2:40035)
    at ce.event.add.v.handle (jquery.min.js:2:38006)

**Comment by Elfrey** [comment]
Да, я еше не обновил до DnD 4, много работы пока(

**Comment by Elfrey** [comment]
@nobi-k @codyspb обновил под днд 4, проверьте пожалуйста.

**Comment by codyspb** [comment]
@Elfrey , отлично, работает, экпортирует 👍
